# Generated by Django 5.0.6 on 2024-08-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("student", "0003_alter_nicknamehistory_user_pointhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Briefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefings",
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TodayPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_attention", models.BooleanField(default=False)),
                ("check_test", models.BooleanField(default=False)),
                ("check_homework", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(default=None)),
                ("expired", models.BooleanField(default=False)),
                (
                    "course_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todaypolls",
                        to="course.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todaypolls",
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
