# Generated by Django 5.0.6 on 2024-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today_poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaypoll',
            name='answered_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
