# Generated by Django 5.0.3 on 2024-07-08 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=10)),
                (
                    "nickname_change_time",
                    models.DateTimeField(
                        default="2024-07-01 12:22:44.398477+09", null=True
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("permission_date", models.DateTimeField(default="7", null=True)),
                ("permission_type", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
