# Generated by Django 5.0.3 on 2024-04-10 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
    ]
