# Generated by Django 5.0.6 on 2024-08-17 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("name", models.CharField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("N", "Nickname"), ("A", "Advertisement")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
