# Generated by Django 5.0.3 on 2024-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_id", models.CharField(max_length=10)),
                ("year_semester", models.CharField(max_length=6)),
                ("course_name", models.CharField(max_length=20)),
                ("course_time", models.CharField(max_length=20)),
                ("instructor", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("course_id", models.CharField(max_length=10)),
                ("year_semester", models.CharField(max_length=6)),
            ],
        ),
    ]
