# Generated by Django 5.0.3 on 2024-05-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_course_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="perimission_date",
            field=models.DateField(null=True),
        ),
    ]
