# Generated by Django 5.0.3 on 2024-05-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_course_timetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=30)),
                ("certification_code", models.CharField(default="", max_length=8)),
                ("certification_check", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="TimeTable",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="student",
            name="role",
        ),
        migrations.AddField(
            model_name="student",
            name="permission_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="permission_type",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
