# Generated by Django 5.0.3 on 2024-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_course_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
