# Generated by Django 5.0.3 on 2024-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_certificationcode_delete_course_delete_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nickname",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
