# Generated by Django 5.0.3 on 2024-05-18 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_student_perimission_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="perimission_date",
            new_name="permission_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="permission",
        ),
    ]
