# Generated by Django 5.0.3 on 2024-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_alter_student_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nickname",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="permission_type",
            field=models.CharField(max_length=10),
        ),
    ]
