# Generated by Django 5.0.3 on 2024-05-24 06:19

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_rename_perimission_date_student_permission_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="TimeTable",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="permission_type",
            field=models.CharField(
                default="0",
                max_length=10,
                validators=[student.models.permission_type_check],
            ),
        ),
    ]
