# Generated by Django 5.0.3 on 2024-05-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_alter_student_nickname_alter_student_permission_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="permission_date",
            field=models.DateTimeField(null=True),
        ),
    ]
