# Generated by Django 5.0.3 on 2024-07-04 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_remove_student_nickname_change_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nickname_change_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 4, 2, 4, 4, 912195, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
