# Generated by Django 5.0.3 on 2024-07-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_alter_student_nickname_change_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nickname_change_time",
            field=models.DateTimeField(verbose_name="2024-07-01 12:22:44.398477+09"),
        ),
    ]
