# Generated by Django 5.0.3 on 2024-07-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0012_alter_student_nickname_change_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nickname_change_time",
            field=models.DateTimeField(
                default="2024-07-01 12:22:44.398477+09", null=True
            ),
        ),
    ]
