# Generated by Django 5.0.4 on 2024-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('course_time', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
