# Generated by Django 5.0.4 on 2024-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='class_day_first',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='class_day_second',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='file_posted',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('posts', models.ManyToManyField(to='course.post')),
            ],
        ),
    ]
