# Generated by Django 5.0.4 on 2024-05-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_comment_is_chosen_course_class_day_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_chosen',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_day_first',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_day_second',
        ),
    ]
