# Generated by Django 5.0.4 on 2024-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_comment_is_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
