# Generated by Django 5.0.4 on 2024-05-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='course_comment',
        ),
    ]
