# Generated by Django 5.0.4 on 2024-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_comment_post_course_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='class_day_first',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='class_day_second',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
    ]
