# Generated by Django 5.0.4 on 2024-05-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_post_course_comment_comment_is_chosen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_day_first',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_day_second',
        ),
    ]
