# Generated by Django 5.0.4 on 2024-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_class_day_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_day_first',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='class_day_second',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.IntegerField(default=None),
        ),
    ]
