version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/devkor-teamb-back
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # 외부 포트 80을 Nginx 컨테이너의 포트 80과 연결
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일을 컨테이너에 연결
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
