version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: kua.c9a6yqqo01jz.ap-northeast-2.rds.amazonaws.com
      POSTGRES_USER: kua
      POSTGRES_PASSWORD: kua
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/devkor-teamb-back
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=kua
      - DB_USER=kua
      - DB_PASSWORD=kua
      - DB_HOST=kua.c9a6yqqo01jz.ap-northeast-2.rds.amazonaws.com
      - DB_PORT=5432
      - EMAIL_PORT = 587
      - EMAIL_HOST_USER = testeuichan@gmail.com
      - EMAIL_HOST_PASSWORD = wrplpvtqhknudaqn
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

volumes:
  postgres_data:
