# Generated by Django 5.0.6 on 2024-07-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='classification',
            field=models.CharField(default='Unclassified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_period',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_room',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_week',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
