# Generated by Django 5.0.6 on 2024-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_table', '0002_remove_course_year_course_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
    ]
