# Generated by Django 5.0.6 on 2024-07-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_table', '0003_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=1000),
        ),
    ]
